# Generated by Django 3.2.7 on 2022-12-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batchId',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
